### PR TITLE
chore: semantic release tweaks

### PR DESCRIPTION
**Pull request by jo**

### CODE REVIEW

**Comment by karl-ehealth** [comment]
Great! Just for reference for others, the sources for those changes are https://github.com/semantic-release/semantic-release/issues/98#issuecomment-143974012 and https://github.com/semantic-release/cli/issues/35 

Lgtm

**Comment by karl-ehealth** [comment]
Also if im not mistaken, we need to apply the same changes in other kazana repos?

**Comment by jo** [comment]
All kazana apps have this now :)

**Comment by jo** [comment]
Thank you @karl-ehealth aka @karlwestin

**Pull request merged**
